### ISSUE TITLE
Stopping the RH RSP server seems to stop the first server

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-rsp#111]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- IntelliJ version:2020.3
- Intellij-rsp extension version: from main branch

## What did you run exactly?

Stopped the RH RSP server

## Actual behavior

The first server is stopped, failed because it was not started, RH server keeps Stopping state

## Expected behavior

RH server should stop

**Comment by robstryker** [comment]
@olkornii I'm not able to replicate this. Are you?

**Comment by olkornii** [comment]
@robstryker 
So steps: ./gradlew runIde -> open RSP Servers tab -> start Red Hat Server Connector -> download some server -> stop Red Hat Server Connector -> Error
Are my steps correctly?

I tried these steps on Fedora and everything was fine. The server connector is stopped. Let me know if you want me to try on win10 (after agreeing with/correcting my steps).

**Comment by robstryker** [comment]
The steps are:

 ./gradlew runIde 

 open RSP Servers tab 

start Red Hat Server Connector 

download some wildfly 

stop Red Hat Server Connector 

Expected Result:  Red Hat Server Connector sets state to stopped. 
Expected Result: No errors. 

Actual Result: Red Hat Server Connector remains started
Actual Result: The first wildfly attempts to stop, which produces an error.

**Comment by robstryker** [comment]
I also wasn't able to replicate. Must have been a weird fluke.
