### ISSUE TITLE
When debugging wildfly, console prints tons of "Connection prematurely closed" messages before succeeding

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-rsp#113]
**Steps:**
1. EXEC: Start Wildfly 24.0.1 in debug mode

**Result:**
Console prints tons of messages "Connection prematurely closed" before it finally succeeds.
![image](https://user-images.githubusercontent.com/25126/136545761-1f0207f2-b001-4e45-8605-dead7b810577.png)

**Comment by robstryker** [comment]
This has been fixed by https://github.com/redhat-developer/intellij-rsp/pull/143

It may still print 1 or 2 but not tons.
