### ISSUE TITLE
Replace icon at JetBrains Marketplace

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-rsp#126]
Currently, the icon used for the RSP plugin on JetBrains Marketplace is the OpenShift icon. We need to replace it with the RSP icon used in VSCode Marketplace.

VSCode Marketplace RSP Icon: https://github.com/redhat-developer/vscode-rsp-ui/blob/main/images/rsp_ui_icon.png

**Comment by robstryker** [comment]
will do
