### ISSUE TITLE
Deployment application disappears after Intellij restart

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-rsp#154]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 38
- IntelliJ version: 2023.2.4
- Intellij-rsp extension version: 0.7.0.113

## What did you run exactly?

create a server (ex. EAP8) -> Add few deployments (as file and as Exploded) -> verify all of them are available on localhost -> Close intellij -> click terminate -> start intellij -> Exploded deployment disappears. It is still available via localhost, but is not in the list under the server

## Actual behavior

Exploded deployment disappears from view.

## Expected behavior

All of deployments available under the server name.

**Comment by robstryker** [comment]
Issue is non-critical.  Issue is better placed in rsp-server:

https://github.com/redhat-developer/rsp-server/issues/716
