### ISSUE TITLE
Not able to install the plugin to the newest IntelliJ Idea (2020.2)

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#20]
<img width="1003" alt="Snímek obrazovky 2020-11-06 v 8 18 07" src="https://user-images.githubusercontent.com/43820055/98337599-24da1a80-2009-11eb-9b67-b97ca37dfa69.png">

**Comment by jeffmaury** [comment]
You are missing the flag that make the plugin compatible with all versions from the version used to build it.

See https://github.com/redhat-developer/intellij-quarkus/blob/master/build.gradle#L25
