### ISSUE TITLE
Only one server has been downloaded when more servers has been selected in the "Download Server Runtime..."

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#24]
- solution could be to allow only one item to be selected

<img width="499" alt="Snímek obrazovky 2020-11-06 v 8 36 09" src="https://user-images.githubusercontent.com/43820055/98338855-24db1a00-200b-11eb-866d-569f144e2c08.png">

**Comment by odockal** [comment]
Fixed.
