### ISSUE TITLE
License agreement dropdown deformed when "Download Runtime..." window's height increases

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#28]
- open the "Download Runtime..." window
- increase the height of the "Download Runtime..." window

<img width="604" alt="Snímek obrazovky 2020-11-06 v 8 43 58" src="https://user-images.githubusercontent.com/43820055/98339734-7c2dba00-200c-11eb-80bc-bbeca2e00840.png">

**Comment by odockal** [comment]
Looks alright on fedora 32.
