### ISSUE TITLE
Show in Browser should be in context menu and also available for deployments

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/intellij-rsp#29]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
When I want to open server in Browser I need to open two other dialogs: Run Server Action
![image](https://user-images.githubusercontent.com/17871936/98339762-8780e580-200c-11eb-9521-540fb73efb55.png)
(Double click do not work here)
And
![image](https://user-images.githubusercontent.com/17871936/98339830-a5e6e100-200c-11eb-85c7-16ff3508290c.png)
(Incorrect window label and also not selected default value and cancel button does not work)

## Why is this needed? 
In context menu it would easier accessible for user and user should be also able to have this for deployments.

**Comment by robstryker** [comment]
We cannot assume which server types have which server actions. Show-in-browser is a custom action and is not official API and so no server type is obligated to expose it as an action. Several don't implement it, for example felix / karaf. Therefore it can't be a top-level action in the context menu.

**Comment by robstryker** [comment]
Not possible to fix based on rsp api.
