### ISSUE TITLE
"Download Runtime..." window (EAP) deformed when resized

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#36]
- disable resize of the window

<img width="650" alt="Snímek obrazovky 2020-11-06 v 9 08 11" src="https://user-images.githubusercontent.com/43820055/98341763-aa60c900-200f-11eb-984f-10b5fb5f7bfe.png">

**Comment by robstryker** [comment]
https://github.com/redhat-developer/intellij-rsp/pull/54  fixes this
