### ISSUE TITLE
[rsp-server API] - Validate the Create Server form without closing it

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/intellij-rsp#37]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
When creating a local server, the `Create a new Server...` form validates inputs after it closes. Meaning if the user makes a mistake and fails validation, they have go through the entire process again.

## Why is this needed? 
So we can fill in the form like civilised beings.

**Comment by robstryker** [comment]
This would require API enhancements to rsp-server and client

**Comment by robstryker** [comment]
Did not require API changes.  Accomplished via UI only. 

https://github.com/redhat-developer/intellij-rsp/commit/05e00949399c5c502b931b92de56bcc1368dc09d
