### ISSUE TITLE
Remove multiselect in the RSP Servers' tree

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#39]
- more servers can be selected -> when you try to delete them, only one will be deleted

<img width="660" alt="Snímek obrazovky 2020-11-06 v 9 13 48" src="https://user-images.githubusercontent.com/43820055/98342299-894ca800-2010-11eb-9fa6-4ed3f5d79161.png">

**Comment by robstryker** [comment]
Anyone know how to do this?
