### ISSUE TITLE
Disable context menu for the "Runtime Server Protocol" item (root of the RSP Servers tree)

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#43]
<img width="466" alt="Snímek obrazovky 2020-11-06 v 9 22 42" src="https://user-images.githubusercontent.com/43820055/98343242-d5e4b300-2011-11eb-9954-00aa857b7b5c.png">

**Comment by robstryker** [comment]
Um... anyone know how to actually do this?

**Comment by robstryker** [comment]
tree.isRootVisible = false
