### ISSUE TITLE
Context Menu Item clicked (first one - delete server) just after context Menu is opened over server

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#67]
[kind/bug]

## What versions of software are you using?
- Operating System: F32
- IntelliJ version: 2020.2
- Intellij-rsp extension version: built from master

## What did you run exactly?
Downloaded RSP -> started it
Create Server from local file system -> EAP 7.3, name it in form, click OK
Server is created
I opened context menu over the eap server with right click and hovered mouse over items...

## Actual behavior
right away first context menu item is chosen (delete server) without me actually pressing left mouse button

## Expected behavior
No item is chosen unless user decide to pick up something

## Any logs, error output, etc?
![ServerDeleted](https://user-images.githubusercontent.com/19164299/101546531-34060c80-39a9-11eb-90ad-eea8f1ecca3f.gif)

**Comment by odockal** [comment]
Right mouse button DOWN event invoke context menu, If I am holding (or I am slow with mouse click) the button down and move the mouse over some item, then I release the button (right mouse button UP event) the item is chosen... Let's call context menu after right mouse button is also released...

**Comment by robstryker** [comment]
WONT_FIX - not rsp issue. I'm not in control of this at all.  This is clearly an issue in IJ.
