### ISSUE TITLE
Add ability to edit basic minishift runtime type configuration, like minishift home, hypervisor, etc.

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#69]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Add ability to edit basic runtime that was passed during runtime creation, ie. minishift home, hypervisor, 

## Why is this needed? 
It is common UI feature, user errors/typos are common when filling in forms. Let user an option to fix/edit params.

**Comment by robstryker** [comment]
Minishift home and hypervisor choice can be modified by right-clicking your server and selecting "Edit Server"
