### ISSUE TITLE
Starting unpreapared CDK/CRC (aka not yet run setup-cdk) does nothing

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#74]
[kind/bug]

## What versions of software are you using?
- Operating System: F32
- IntelliJ version: 2020.2
- Intellij-rsp extension version: 

## What did you run exactly?
1. Have created CDK server adapter (using local cdk 1.14)
2. Start it 

## Actual behavior
Nothing

## Expected behavior
Reports that it requires to call setup-cdk first

**Comment by odockal** [comment]
I also found out that adding CRC and trying to start it does nothing... I believe that some warning that one should run setup-crc operation is not happening. Though,If I call it, it happens, so I then try to start crc.. and nothing happens, this time output channel opens up, but that is all. And I do not know what is wrong...

**Comment by robstryker** [comment]
Seems there's some weird error where if the process ends quickly before it had a chance to process / display the output, it closes the terminal as empty.
