### ISSUE TITLE
[rsp api] [local server] Add browse button into the forms (crc as one example) and open up native/whatever dialog to browse for files

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#75]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Add browse buttons into the forms when user is creating server adapters and is passing some file's path
CRC example where it can be added:
![Screenshot_20201214_162819](https://user-images.githubusercontent.com/19164299/102100158-68eee500-3e29-11eb-9599-1f87650e53ad.png)

## Why is this needed? 
It is quite user friendly action.

**Comment by robstryker** [comment]
API isn't designed to indicate anything is a 'file' or browseable. Would require API changes.

**Comment by odockal** [comment]
but you can browse for path and then validate it?

**Comment by robstryker** [comment]
The UI has no idea which text field should have a 'browse' next to it or not. It just knows "Display a text field" or "Display a label" or "Display a Combo".  It can't put a browse button next to each and every text field, right? If the field is username or url or whatever, the UI can't just throw a browse button next to everything. It should only put a browse button next to things that the UI has been told "We are asking for a file here." 

And that's not part of the API currently.

**Comment by robstryker** [comment]
![image](https://user-images.githubusercontent.com/630383/224424857-1b2efa19-26dc-42a9-b766-779afe8b7848.png)
Fixed
