### ISSUE TITLE
EAP 7.3 is marked 'Starting' even though log says it has been started and it goes to stopped in a while when port is other than 8080

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-rsp#76]
[kind/bug]

## What versions of software are you using?
- Operating System: F32
- IntelliJ version: 2020.2
- Intellij-rsp extension version: built from master: 0a6adc39d2cabbb26568ff92a4bf2c341c521faa

## What did you run exactly?
Created EAP 7.3 server adapter
Server action -> Edit configuration file -> change `<socket-binding name="http" port="${jboss.http.port:8080}"/>` to `<socket-binding name="http" port="${jboss.http.port:8081}"/>`
Start EAP adapter

## Actual behavior
State is 'Starting', though, log says it is started. I can see localhost welcome page. After some time, it stops. And it is definitely stopped. Seems like some timeout is reached and it stops the server.

## Expected behavior
When it is started, it is started.

**Comment by robstryker** [comment]
Users must customize the host/port in the server editor.  Functionality was added June 7th 2019 in rsp-server.   https://github.com/redhat-developer/rsp-server/commit/97b0bfb4d9155428bd01c25c631b30e52f3a4757
