### ISSUE TITLE
Start/Stop a server keeps creating new terminal tabs

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-rsp#87]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Terminal tabs

## Why is this needed? 

Every time i start/stop a server, the terminal creates a new tab. It would be great if we could re-use an existing tab related to that server. 
![image](https://user-images.githubusercontent.com/49404737/117308484-de635c80-ae81-11eb-8c14-8e248f954904.png)

**Comment by robstryker** [comment]
So... not 100% sure how to handle this. We spawn a new terminal for each process that is launched. We don't group them by purpose. All the UI knows is a new process was launched. I might be able to add some level of API enhancement / properties to let the UI know when the process is created if it's a part of a set of single-terminal processes (startup, shutdown, etc) that should re-use the terminals? 

That'd be an enhancement in rsp-server though.

**Comment by lstocchi** [comment]
Can't we associate a terminal to a server and re-use the same terminal like in vscode? If you try to `restart` a server two terminals get opened for a "single" operation. It's a `stop and start` but from a user perspective it is a single click. BTW it is not a bug, just reported this as i saw a discrepancy with vscode

**Comment by robstryker** [comment]
I mean, we COULD... but... some servers might spawn multiple processes. I know, none of OURS do, but some COULD. So reusing the same terminal all the time has the potential to cause multiple processes using the same output channel. 

In fact, even for our servers, using a single output channel could have our shutdown command writing to the same console as our startup command. So, I mean, this should require some thought. 

I'm thinking of adding a field to the output indicating not just a process id but a category id (for example, server.someid.output.source=startup or something like this.  Then we could declare only 1 output channel of each "source" ?

**Comment by robstryker** [comment]
Seems to me these are being re-used now?  I can't figure out why, but, it's not opening 100 new windows... so... that's a freebie i guess?
