### ISSUE TITLE
Credentials dialog keeps reopening even when cancel/close is selected

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-rsp#88]
[kind/bug]

## What did you run exactly?

I tried to create a RedHat Jboss EAP 7.30

## Actual behavior

When you are asked to insert your creadentials, you cannot cancel/close the dialog. It keeps reopening. If you don't insert the correct credentials you are stuck

![image](https://user-images.githubusercontent.com/49404737/118240302-21818900-b49b-11eb-9344-e3d00f86621d.png)

## Expected behavior

If i cancel/close it it shouldn't reopen

**Comment by robstryker** [comment]
Likely fixed by * 0024c29 - Fixes #91 - canceling download runtime workflow gets stuck in loop (2 hours ago) <Rob Stryker>
