### ISSUE TITLE
License text is wrong when downloading CDK server

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-rsp#89]
[kind/bug]

## What did you run exactly?

I tried to create a CDK server

## Actual behavior

I don't see the correct license text
![image](https://user-images.githubusercontent.com/49404737/118240884-ce5c0600-b49b-11eb-9195-173314aaef22.png)

## Expected behavior
I should see the correct license text

P.S: I guess the same is for CRC

**Comment by robstryker** [comment]
https://github.com/jboss-developer/jboss-stacks/pull/172
