### ISSUE TITLE
[rsp api] [Download-runtime] Cannot search the pull secret file when creating a CRC server

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-rsp#90]
[kind/bug]

## What did you run exactly?

I tried to create CRC

## Actual behavior

When i need to select my pull secret file i only see a basic textbox
![image](https://user-images.githubusercontent.com/49404737/118241240-36aae780-b49c-11eb-8a3e-85fd81759064.png)

## Expected behavior

It would be great if i could open the filesystem dialog so to select the pull secret file manually without typing its path. 
Also it would be great to have a link to where i can download my pull secret file or a link to a page where it explains how to download my pull secret file.

**Comment by robstryker** [comment]
Download runtime workflow API currently does not support properties to indicate a filepicker instead fo a text box filler. This is a protocol flaw and will need an enhancement to fix it.

**Comment by robstryker** [comment]
![image](https://user-images.githubusercontent.com/630383/224424768-4a821a6a-e552-4345-9a84-98c1936e305f.png)

looks like it was solved.
