### ISSUE TITLE
Pull secret file dialog keeps reopening when trying to close it

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-rsp#91]
[kind/bug]

## What did you run exactly?

I tried to create CRC

## Actual behavior

I cannot close the pull secret file dialog. The dialog keeps reopening
![image](https://user-images.githubusercontent.com/49404737/118241562-973a2480-b49c-11eb-90f3-36c1bcffd92a.png)

## Expected behavior

When I close/cancel the pull secret dialog the dialog shouldn't reopen

**Comment by robstryker** [comment]
Can you tell me more about your workflow / how you got to this point?

**Comment by lstocchi** [comment]
Right-click on `Red Hat Server Connector` -> Download server -> pick the last CRC -> accept the license
At this point you should be at the step where you need to insert your pull secret file. If you click on cancel or close, the dialog keeps reopening.
